#spring.jpa.database=MYSQL
## Show or not log for each sql query
##spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update